FROM python:3.10-buster
LABEL maintainer="banco_api"

RUN apt-get update

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 8000
ENTRYPOINT ["uvicorn"]
CMD ["main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
